name: release
on:
  push:
    branches: [main]
  workflow_dispatch: {}

jobs:
  build-push:
    permissions:
      contents: read
      id-token: write
    uses: wowjeeez/terraform/.github/workflows/build-push.yml@main
    with:
      service: babylon
      ar_host: ${{ secrets.AR_HOST }}
      ar_project: ${{ secrets.AR_PROJECT }}
      wif_provider: ${{ secrets.WIF_PROVIDER }}
      ci_service_account: ${{ secrets.CI_SERVICE_ACCOUNT }}
